function fit_out = BuildOutputStruct(state, SNR_max, SNR_density_max)
% BUILDOUTPUTSTRUCT  Assemble the fit_out struct expected by callers.
%
%   Mirrors the legacy CopterCurrents fit_out shape (FG_fit / SG_fit with
%   the per-pixel 2D fields left empty; the scalar fit lives in U / loss).

    FG_fit = struct( ...
        'signal_2D',          [], ...
        'noise_2D',           [], ...
        'signal_nvalues_2D',  [], ...
        'noise_nvalues_2D',   [], ...
        'SNR_2D',             [], ...
        'SNR_density_2D',     [], ...
        'Ux_fit',             state.best_U(1), ...
        'Uy_fit',             state.best_U(2), ...
        'SNR_max',            SNR_max, ...
        'SNR_density_max',    SNR_density_max, ...
        'Ux_2D',              [], ...
        'Uy_2D',              [] );
    
    SG_fit = FG_fit;
    
    fit_out = struct( ...
        'FG_fit',          FG_fit, ...
        'SG_fit',          SG_fit, ...
        'U',               state.best_U, ...
        'loss',            state.best_L, ...
        'adaptive_params', struct( ...
            'L_initial',     state.L_initial, ...
            'step_initial',  state.step_initial ), ...
        'timing',          struct( ...
            'total_time',     state.total_time, ...
            'iter_times',     state.iter_times, ...
            'mean_iter_time', state.mean_iter_time ) );
end
